INSERT INTO users."user" (id, active, admin_entity, chat_id, f_name, l_name, user_group, user_language, user_nick_name,
                          user_option_id, is_defined)
VALUES (120, true, false, 972344705, 'Mihai', 'Cojusnean', 'MI31Z', 'en', null, null, true);

ALTER TABLE users.user_option DROP CONSTRAINT user_option_user_user_option_id_fk;

INSERT INTO users.user_option (id, audience_selected, group_selected, teacher_selected, user_id) VALUES (121, false, true, false, 120);
INSERT INTO users.user_option (id, audience_selected, group_selected, teacher_selected, user_id) VALUES (122, false, false, true, null);
INSERT INTO users.user_option (id, audience_selected, group_selected, teacher_selected, user_id) VALUES (123, false, true, false, null);
INSERT INTO users.user_option (id, audience_selected, group_selected, teacher_selected, user_id) VALUES (124, true, false, false, null);

UPDATE users."user" SET user_option_id = 121 WHERE id = 120;

ALTER SCHEMA parsing RENAME TO lesson_parsing;

INSERT INTO lesson_parsing.teacher (id, name) VALUES (3, 'Abramciuc Maria Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1750, 'Șaganean Gabriela Xxx');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (5, 'Amarfii-Railean Nelli Valeriu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1171, 'Andruşco Mariana Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1228, 'Arlet-Vovc Aliona Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1316, 'Avram Alexandru Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (965, 'Babii Leonid Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (38, 'Baciu Daniela Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (214, 'Baciu Inga Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (20, 'Baghici Nicoleta Nicu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (33, 'Balanici Alexandru Mihai');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (16, 'Balanici Lucia Visarion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (36, 'Balînschi Andrei Valentin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1235, 'Bantoş Ana Anton');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (925, 'Bejan Angela Fiodor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1772, 'Bejenari Vasilii Anatolie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (311, 'Beşliu Vitalie Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (826, 'Beţivu Aurelia Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1619, 'Bîrlădeanu Virgiliu Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (37, 'Bogdan Silvia Leonid');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1170, 'Boincean Boris Pavel');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (25, 'Boişteanu Eduard Alexei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (31, 'Botnari Elena Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (11, 'Brajuc Vladimir Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (30, 'Branaşco Natalia Leonid');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (309, 'Briceag Silvia Sergiu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (901, 'Briţchi Aliona Eugeniu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1215, 'Buga Oleg Simion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (89, 'Bularga Tatiana Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (41, 'Bulat Gheorghe Tudor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (17, 'Bulgacova Irina Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (959, 'Butnaru Roman Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (35, 'Buzdugan Vasile Constantin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (34, 'Buzinschi Ion Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (72, 'Cabac Eugeniu Valeriu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (811, 'Cabac Ghennadi Valeri');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1008, 'Cabac Lina Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (44, 'Cabac Ludmila Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (78, 'Cabac Valeriu Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (57, 'Călăraş Angela Tudor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (79, 'Caliga Marina Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (47, 'Canţer Nicoletta Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (56, 'Capcelea Victor Diomid');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1603, 'Carp Viorica Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (76, 'Cazac Ianina Ian');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (955, 'Cazacu Daniela Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (82, 'Cazacu Valentin Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (45, 'Cebotaroş Viorica Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (52, 'Ceh Oxana Valerie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (966, 'Chihai Jana Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (81, 'Chilat Sergiu Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (74, 'Chira Oxana Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (418, 'Chiriţa Mariana Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (60, 'Chiseliov Lilia Anatol');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (172, 'Cibotaru Oxana Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1699, 'Cimili Eduard Xxx');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (51, 'Ciobanu Ina Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (64, 'Ciobanu Ion Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (43, 'Ciobanu Lora Pavel');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (933, 'Ciobu Corin Mircea');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (812, 'Ciorici Catalina Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (90, 'Clim Tudor Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1366, 'Cociug Victoria Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (32, 'Codreanu Aurelia Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1730, 'Cojocari Ion Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1473, 'Cojocari Ludmila Dmitri');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (66, 'Cojocaru Igor Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1703, 'Colodrovschi Natașa Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (440, 'Condrat Viorica Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1754, 'Condraticova Liliana Eduard');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1397, 'Corcenco Aliona Fiodor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (145, 'Corcevoi Maria Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1432, 'Coreţchi Boris Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (49, 'Coşciug Angela Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (800, 'Costin Iraida Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (117, 'Coşulean Liliana Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (931, 'Cosumov Marina Veaceslav');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (349, 'Cotîlevscaia Tatiana Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (212, 'Cotos Ludmila Leonid');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1459, 'Covalciuc Ion Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (304, 'Covalciuc Lucia Grigore');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (48, 'Cozniuc Octavian Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (802, 'Cracan Cornel Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (63, 'Craevscaia-Derenova Cristina Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (65, 'Creciun Aliona Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (306, 'Crişciuc Viorica Eugen');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (77, 'Crudu Cristina Sergiu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (70, 'Crugliţchi Tatiana Bronislav');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1187, 'Curicheru Galina Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1158, 'Cuţulab Ala Mihai');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (100, 'Dănoi Ion Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (95, 'Dinescu Victoria Valentin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (96, 'Dolgov Veaceslav Ghenadie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (299, 'Dumbravanu Lilia Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1415, 'Dumbrăveanu Ludmila Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (342, 'Dumbrăveanu Radu Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1464, 'Dumitraşcu Dumitru Vasilii');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (99, 'Dzechiş Svetlana Ivan');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (969, 'Edu Inga Iurie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (106, 'Enciu Valentina Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1420, 'Eremciuc Ghenadie Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (108, 'Faigher Anatolie Anatolie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (109, 'Filipp Svetlana Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (134, 'Foca Eugenia Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (303, 'Focşa Ion Gherasim');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (132, 'Fotescu Emil Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (960, 'Gagim Ion Tudor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (111, 'Galat Galina Andrei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (112, 'Galiţ Valeriu Valeriu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (114, 'Garbuz Vasile Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1168, 'Garbuz Veronica Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (115, 'Gaşiţoi Natalia Alexandru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (116, 'Gavajuc Stela Liviu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1702, 'Gherasim Cristina Xxx');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (302, 'Gînju Tatiana Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (529, 'Glebov Ana Alexandru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (118, 'Gorbani Stella Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (886, 'Gorbul Valeriu Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (817, 'Gorea Adela Tudor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (119, 'Gorea Tatiana Eugeniu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1525, 'Gorlenco Fiodor Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (139, 'Graneţkaia Lilia Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1752, 'Gribincea Tatiana Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (129, 'Grigoraş Ruslan Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1758, 'Grimailo Nelea Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (124, 'Griţco Diana Tudor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (131, 'Griţunic-Mirca Diana Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (300, 'Gupalova Elena Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (122, 'Guranda Elvira Alexandru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (125, 'Guţu Natalia Filip');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1303, 'Guzgan Dorin Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (845, 'Hariton Natalia Ivan');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (144, 'Hîrbu Arefa Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1326, 'Hmelevscaia Svetlana Alexandr');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1401, 'Iaţco Ala Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1160, 'Iavorschi-Iacoban Corina Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (810, 'Ignatenco Diana Anatolie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (141, 'Ignatiuc Iulia Simion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (982, 'Jacota-Dragan Olga Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1382, 'Janu Natalia Ştefan');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (142, 'Jitaru Lucian Valentin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (80, 'Kononova Tatiana Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (73, 'Krugliţki Mihaela Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (565, 'Lacusta Elena Tudor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (146, 'Leahu Nicolae Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (148, 'Leahu Raisa Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (150, 'Luchian Vasile Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1604, 'Macrii Lucia Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (171, 'Marşalcovschi Teo-Teodor Iacob');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (151, 'Mascaliuc Victoria Fiodor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (908, 'Masliuc Alina Evgheni');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (598, 'Melnic Svetlana Valeriu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1755, 'Mihalache Iurie Ivan');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1724, 'Milicenco Stela Ștefan');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (156, 'Moglan Diana Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (157, 'Mohorea Efim Panait');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1701, 'Molcosean Ana Grigore');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1014, 'Morari Alexandru Andrei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (159, 'Morari Marina Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (162, 'Moraru Anatol Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (163, 'Movilă Irina Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (166, 'Muntean Ana Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (175, 'Nacai Lilia Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (180, 'Nasu Ilie Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (176, 'Neagu Gheorghe Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (179, 'Negara Corina Valeriu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (174, 'Nichitcin Corina Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (168, 'Niculcea Ecaterina Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (178, 'Novac Adela Sava');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (181, 'Odinokaia Ina Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (973, 'Ojegov Alexandr Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (182, 'Olaru Ion Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (183, 'Oleiniuc Maria Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1267, 'Oprea Mariana Marin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (972, 'Orlov Maria Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (184, 'Pădureac Lidia Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1749, 'Paiul Irina Vitalie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1751, 'Paladi Daniela Valerian');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (958, 'Panco Tatiana Ivan');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1683, 'Parahonco Liudmila Veaceslav');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (208, 'Parnovel Valeriu Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (189, 'Pereteatcu Maria Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (190, 'Pereteatcu Pavel Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (899, 'Petic Mircea Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1351, 'Piatkowska Kinga Kazimierz');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (296, 'Pînzari Veaceslav Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (215, 'Pînzaru Natalia Anatolie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (209, 'Plohotniuc Eugeniu Filip');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (222, 'Pomelnicova Ana Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (226, 'Popa Gheorghe Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (196, 'Popa Mihail Eugen');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1773, 'Popa Valeriu Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (192, 'Popa Viorica Constantin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (193, 'Popov Lidia Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (203, 'Popovici Vitalie Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (194, 'Postolache Victoria Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (859, 'Postolachi Iulia Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (197, 'Postolachi Svetlana Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (198, 'Priţcan Valentina Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (220, 'Puiu Dina Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (229, 'Răciula Lilia Alexei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (228, 'Răciula Ludmila Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (143, 'Razmeriţa Liubovi Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1531, 'Romandaş Nicolai Trofim');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (207, 'Rotari Tatiana Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (232, 'Rotaru Andrei Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (235, 'Rusnac Vladislav Boris');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (236, 'Rusov Veronica Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1766, 'Rusu Galina Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1455, 'Rusu Lucia Valeriu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1336, 'Rusu Natalia Mihai');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (237, 'Rusu Vitalie Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (238, 'Rusu Vladimir Ilie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (262, 'Sacaliuc Nina Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (239, 'Sainenco Ala Petru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (266, 'Şaragov Vasilii Andrei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (250, 'Şcerbacova Tatiana Eugeniu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (249, 'Secrieru Luminiţa Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1765, 'Seiciuc Vladislav Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (243, 'Sicur Piotr Iosif');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (252, 'Sirota Elena Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (258, 'Skutniţki Olesea Vladimir');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (254, 'Şleahtiţchi Maria Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (940, 'Şleahtiţchi Mihail Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (251, 'Slutu Rodica Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (866, 'Şova Tatiana Valentin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (253, 'Spatari Mariana Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (264, 'Stadnic Stanislav Stepan');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (244, 'Stanţieru Oxana Vasile');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (245, 'Stanţieru Svetlana Andrei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (260, 'Stici Dina Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (246, 'Stoian Dumitru Dumitru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1023, 'Suslenco Alina Andrei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (247, 'Suzanskaia Tatiana Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1764, 'Taban Elena Pavel');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (801, 'Tăbîrţă Alina Constantin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (946, 'Talpă Serghei Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (268, 'Ţaralungă Victoria Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1153, 'Ţaranu Ludmila Fiodor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (285, 'Ţaulean Micaela Valerian');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (276, 'Tcaci Carolina Constantin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (271, 'Tetelea Margarita Sergiu');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (283, 'Teterina Marina Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (274, 'Ţîcău Vitalie Stepan');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (284, 'Ţîganaş Ion Pavel');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (277, 'Topală Pavel Alexei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (273, 'Trinca Lilia Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (278, 'Trusevici Alla Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (286, 'Ursu Vitalie Alexandru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (288, 'Varzari Elena Nicolae');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (791, 'Vovnenciuc Olga Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1146, 'Vozian Valeriu Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1229, 'Vrabie Corneliu Mihail');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (291, 'Vrabie Diana Alexei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (876, 'Zabulica Ana Alexandru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (1692, 'Zamfir Vasile Gheorghe');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (348, 'Zastînceanu Liubov Andrei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (350, 'Zolotariov Elena Constantin');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (351, 'Zorilo Larisa Ion');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (848, 'Moraru Victor Vorfolomei');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (2261, 'Morari Dmitrie');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (2263, 'Adamciuc Aurelia');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (2264, 'Grigor Victor');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (2266, 'Crudu Valeria');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (2269, 'Molcosean Alexandru');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (2271, 'Chihai Nelea');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (10068, 'Aidina Elena');
INSERT INTO lesson_parsing.teacher (id, name) VALUES (10069, 'Frunză Alina');

ALTER TABLE lesson_parsing."group" ADD COLUMN group_id BIGINT;

INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (936, '101', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (937, '102', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (938, '103', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (939, '104', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (965, '105', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (964, '201', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (967, '202', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (968, '203', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (969, '204', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (718, 'AG51R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (104, 'AP11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (82, 'AP11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (141, 'AP21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (375, 'AP31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (479, 'AP41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (124, 'AS11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (114, 'AS11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (152, 'AS21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (382, 'AS31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (305, 'AS41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (79, 'BA11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (446, 'BA12R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (402, 'BA21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (166, 'BA21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (459, 'BA22R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (458, 'BA31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (304, 'BA31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (527, 'BA32R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (447, 'BA41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (775, 'BL F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (776, 'CM F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (450, 'CT11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (75, 'CT11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (461, 'CT21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (135, 'CT21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (566, 'CT31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (300, 'CT31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (651, 'CT41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (102, 'DR11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (84, 'DR11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (103, 'DR12R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (85, 'DR12Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (249, 'DR13R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (86, 'DR13Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (963, 'DR14R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (140, 'DR21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (182, 'DR21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (146, 'DR22R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (193, 'DR22Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (948, 'DR23R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (369, 'DR23R1', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (373, 'DR31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (314, 'DR31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (374, 'DR32R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (317, 'DR32Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (487, 'DR33R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (481, 'DR41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (321, 'DR41Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (482, 'DR42R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (324, 'DR42Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (604, 'DR51R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (605, 'DR52R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (235, 'DV11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (914, 'DV41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (871, 'DV51R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (109, 'EC11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (106, 'EC11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (142, 'EC21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (379, 'EC31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (95, 'EF11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (957, 'EF33Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (89, 'EG11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (169, 'EG21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (878, 'EG34Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (660, 'EG44Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (931, 'EGT11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (954, 'EGT21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (958, 'EGT35Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (980, 'EI F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (516, 'EI11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (584, 'EI21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (585, 'EI31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (586, 'EI41Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (945, 'EM F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (979, 'EMT F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (430, 'ES11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (483, 'ES21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (921, 'ES33Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (825, 'ES43Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (537, 'ET31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (449, 'ET41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (77, 'FB11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (162, 'FB21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (417, 'FB31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (96, 'FE11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (173, 'FE21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (669, 'FE36Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (676, 'FE45Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (929, 'FET11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (955, 'FET21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (774, 'FZ  F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (565, 'FZ11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (439, 'GB11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (542, 'GB11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (361, 'GB21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (165, 'GB21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (334, 'GB31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (335, 'GB41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (378, 'GB51R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (91, 'GE11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (930, 'GET11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (953, 'GET21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (663, 'GET46Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (909, 'IA F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (946, 'IA1 F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (704, 'IM11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (419, 'IM11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (823, 'IM21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (720, 'IM21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (868, 'IM31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (836, 'IM31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (867, 'IM41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (866, 'IM41Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (913, 'IM51R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (56, 'IP11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (51, 'IP11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (523, 'IP41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (443, 'IS11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (53, 'IS11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (526, 'IS21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (568, 'IS31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (262, 'IS31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (529, 'IS41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (956, 'JR21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (874, 'JR38Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (782, 'LG F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (781, 'LLE F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (778, 'LLF F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (770, 'LLR F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (779, 'LLRA F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (981, 'LLRM F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (769, 'LLRS  F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (780, 'LLU F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (982, 'LLU F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (908, 'MAC F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (777, 'ME F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (530, 'MI11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (50, 'MI11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (533, 'MI31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (259, 'MI31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (534, 'MI41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (535, 'MI51R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (905, 'MP F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (790, 'MT F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (130, 'MZ11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (128, 'MZ11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (139, 'MZ21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (397, 'MZ31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (349, 'MZ31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (507, 'MZ41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (521, 'PE11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (112, 'PE11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (113, 'PE12Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (239, 'PE21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (337, 'PE31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (341, 'PE41Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (505, 'PE41Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (987, 'PE43ZT', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (988, 'PÎP CF', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (771, 'PIP F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (940, 'PÎP F(rom)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (853, 'PÎP F(rus)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (786, 'PÎP RF', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (933, 'PÎP RF(rom)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (941, 'PÎP RF(rus)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (943, 'PP CF', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (992, 'PP F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (852, 'PP F(rus)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (787, 'PP RF', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (942, 'PP RF(rom)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (843, 'PP RF(rus)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (111, 'PP11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (122, 'PP12R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (224, 'PP12Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (841, 'PP13R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (149, 'PP21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (238, 'PP21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (156, 'PP22R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (835, 'PP22Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (840, 'PP23R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (394, 'PP31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (336, 'PP31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (395, 'PP32R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (549, 'PP32Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (396, 'PP33R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (510, 'PP41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (339, 'PP41Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (513, 'PP42R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (340, 'PP42Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (514, 'PP43R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (538, 'PP51R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (539, 'PP52R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (540, 'PP53R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (773, 'PS F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (243, 'PS21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (328, 'PS31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (174, 'RE21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (289, 'RE41Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (901, 'RET21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (60, 'RF11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (616, 'RF21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (654, 'RF31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (722, 'RG21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (72, 'RO11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (145, 'RO21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (384, 'RO31R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (435, 'RO41R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (932, 'RU11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (947, 'RU21R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (474, 'RU32R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (570, 'RU42R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (927, 'SE11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (959, 'SE21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (655, 'SE32Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (725, 'SE42Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (493, 'TA11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (984, 'TAI 1F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (985, 'TAI 2F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (983, 'TAI F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (906, 'TIC F', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (896, 'TP11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (912, 'TP21Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (949, 'TP31Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (970, 'UC11R', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (960, 'UE11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (962, 'UR11Z', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (19, 'AA11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (134, 'AW21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (153, 'BS11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (197, 'BS21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (12, 'CP11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (37, 'CP21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (22, 'CT11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (29, 'CT21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (88, 'DB21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (279, 'DG11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (284, 'DLF11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (62, 'DM11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (267, 'DO11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (285, 'DO21M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (273, 'DO21M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (256, 'DR11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (159, 'DR21M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (161, 'DR21M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (282, 'DRA11M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (283, 'DRA11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (292, 'DRA21M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (277, 'DS11M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (276, 'DS11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (275, 'DU11M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (286, 'DU21M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (57, 'EA11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (78, 'EA21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (229, 'IDP11M (120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (230, 'IDP11M (90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (254, 'IDP21M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (280, 'LAE11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (15, 'MAP11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (40, 'MAP21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (9, 'ME11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (94, 'ME12M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (180, 'ME13M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (237, 'ME13M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (32, 'ME21M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (115, 'ME22M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (189, 'ME23M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (236, 'ME23M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (187, 'MEI11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (192, 'MEI21M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (190, 'MEI21M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (247, 'MET11M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (246, 'MET21M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (222, 'MET21M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (20, 'MF11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (26, 'MF21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (270, 'MP11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (10, 'PF11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (33, 'PF21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (11, 'PJ11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (34, 'PJ21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (81, 'PW11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (120, 'PW21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (177, 'RM11M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (178, 'RM11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (255, 'RM21M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (66, 'SA11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (196, 'SA21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (18, 'SP11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (251, 'SP12M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (41, 'SP22M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (221, 'TI21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (186, 'SP21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (268, 'DO11M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (241, 'IDP21M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (248, 'DR11M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (129, 'DDA21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (274, 'DU11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (167, 'LAE21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (55, 'DB11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (272, 'MP21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (198, 'MET11M(90)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (133, 'AW11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (154, 'MEI11M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (240, 'RM21M(120)', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (121, 'DDA11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (116, 'DM21M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (58, 'TI11M', null);
INSERT INTO lesson_parsing."group" (id, name, group_id) VALUES (278, 'DE11M', null);

INSERT INTO lesson_parsing.daily_parameters (id, day, parameters_date, semester, week) VALUES (8832, '4', '2021-03-26 +01', '2', '8');

INSERT INTO lesson_parsing.audience (id, name) VALUES (233, 'Aula');
INSERT INTO lesson_parsing.audience (id, name) VALUES (242, 'Aula 1');
INSERT INTO lesson_parsing.audience (id, name) VALUES (39, 'Aula 100');
INSERT INTO lesson_parsing.audience (id, name) VALUES (52, 'Aula 101');
INSERT INTO lesson_parsing.audience (id, name) VALUES (261, 'Aula 1010');
INSERT INTO lesson_parsing.audience (id, name) VALUES (17, 'Aula 102');
INSERT INTO lesson_parsing.audience (id, name) VALUES (19, 'Aula 103');
INSERT INTO lesson_parsing.audience (id, name) VALUES (90, 'Aula 104');
INSERT INTO lesson_parsing.audience (id, name) VALUES (48, 'Aula 105');
INSERT INTO lesson_parsing.audience (id, name) VALUES (309, 'Aula 13');
INSERT INTO lesson_parsing.audience (id, name) VALUES (44, 'Aula 140');
INSERT INTO lesson_parsing.audience (id, name) VALUES (15, 'Aula 141');
INSERT INTO lesson_parsing.audience (id, name) VALUES (22, 'Aula 141a');
INSERT INTO lesson_parsing.audience (id, name) VALUES (255, 'Aula 142');
INSERT INTO lesson_parsing.audience (id, name) VALUES (206, 'Aula 143');
INSERT INTO lesson_parsing.audience (id, name) VALUES (40, 'Aula 144');
INSERT INTO lesson_parsing.audience (id, name) VALUES (310, 'Aula 145');
INSERT INTO lesson_parsing.audience (id, name) VALUES (24, 'Aula 146');
INSERT INTO lesson_parsing.audience (id, name) VALUES (25, 'Aula 148');
INSERT INTO lesson_parsing.audience (id, name) VALUES (21, 'Aula 150');
INSERT INTO lesson_parsing.audience (id, name) VALUES (23, 'Aula 158');
INSERT INTO lesson_parsing.audience (id, name) VALUES (294, 'Aula 208');
INSERT INTO lesson_parsing.audience (id, name) VALUES (2, 'Aula 209');
INSERT INTO lesson_parsing.audience (id, name) VALUES (49, 'Aula 210');
INSERT INTO lesson_parsing.audience (id, name) VALUES (12, 'Aula 214');
INSERT INTO lesson_parsing.audience (id, name) VALUES (33, 'Aula 221');
INSERT INTO lesson_parsing.audience (id, name) VALUES (6, 'Aula 222');
INSERT INTO lesson_parsing.audience (id, name) VALUES (3, 'Aula 223');
INSERT INTO lesson_parsing.audience (id, name) VALUES (1, 'Aula 224');
INSERT INTO lesson_parsing.audience (id, name) VALUES (278, 'Aula 229');
INSERT INTO lesson_parsing.audience (id, name) VALUES (254, 'Aula 230');
INSERT INTO lesson_parsing.audience (id, name) VALUES (46, 'Aula 231');
INSERT INTO lesson_parsing.audience (id, name) VALUES (7, 'Aula 232');
INSERT INTO lesson_parsing.audience (id, name) VALUES (4, 'Aula 233');
INSERT INTO lesson_parsing.audience (id, name) VALUES (14, 'Aula 235');
INSERT INTO lesson_parsing.audience (id, name) VALUES (10, 'Aula 236');
INSERT INTO lesson_parsing.audience (id, name) VALUES (9, 'Aula 238');
INSERT INTO lesson_parsing.audience (id, name) VALUES (55, 'Aula 239');
INSERT INTO lesson_parsing.audience (id, name) VALUES (274, 'Aula 3');
INSERT INTO lesson_parsing.audience (id, name) VALUES (174, 'Aula 303');
INSERT INTO lesson_parsing.audience (id, name) VALUES (30, 'Aula 310');
INSERT INTO lesson_parsing.audience (id, name) VALUES (171, 'Aula 314');
INSERT INTO lesson_parsing.audience (id, name) VALUES (240, 'Aula 326');
INSERT INTO lesson_parsing.audience (id, name) VALUES (36, 'Aula 327');
INSERT INTO lesson_parsing.audience (id, name) VALUES (56, 'Aula 328');
INSERT INTO lesson_parsing.audience (id, name) VALUES (58, 'Aula 329');
INSERT INTO lesson_parsing.audience (id, name) VALUES (199, 'Aula 330');
INSERT INTO lesson_parsing.audience (id, name) VALUES (59, 'Aula 331');
INSERT INTO lesson_parsing.audience (id, name) VALUES (60, 'Aula 334');
INSERT INTO lesson_parsing.audience (id, name) VALUES (95, 'Aula 335');
INSERT INTO lesson_parsing.audience (id, name) VALUES (205, 'Aula 338');
INSERT INTO lesson_parsing.audience (id, name) VALUES (61, 'Aula 340');
INSERT INTO lesson_parsing.audience (id, name) VALUES (295, 'Aula 342');
INSERT INTO lesson_parsing.audience (id, name) VALUES (62, 'Aula 343');
INSERT INTO lesson_parsing.audience (id, name) VALUES (63, 'Aula 344');
INSERT INTO lesson_parsing.audience (id, name) VALUES (179, 'Aula 345');
INSERT INTO lesson_parsing.audience (id, name) VALUES (296, 'Aula 351');
INSERT INTO lesson_parsing.audience (id, name) VALUES (64, 'Aula 352');
INSERT INTO lesson_parsing.audience (id, name) VALUES (66, 'Aula 353');
INSERT INTO lesson_parsing.audience (id, name) VALUES (65, 'Aula 354');
INSERT INTO lesson_parsing.audience (id, name) VALUES (96, 'Aula 355');
INSERT INTO lesson_parsing.audience (id, name) VALUES (67, 'Aula 361');
INSERT INTO lesson_parsing.audience (id, name) VALUES (97, 'Aula 362');
INSERT INTO lesson_parsing.audience (id, name) VALUES (45, 'Aula 363');
INSERT INTO lesson_parsing.audience (id, name) VALUES (98, 'Aula 364');
INSERT INTO lesson_parsing.audience (id, name) VALUES (219, 'Aula 369');
INSERT INTO lesson_parsing.audience (id, name) VALUES (99, 'Aula 371');
INSERT INTO lesson_parsing.audience (id, name) VALUES (68, 'Aula 372');
INSERT INTO lesson_parsing.audience (id, name) VALUES (69, 'Aula 373');
INSERT INTO lesson_parsing.audience (id, name) VALUES (70, 'Aula 374');
INSERT INTO lesson_parsing.audience (id, name) VALUES (34, 'Aula 375');
INSERT INTO lesson_parsing.audience (id, name) VALUES (225, 'Aula 376');
INSERT INTO lesson_parsing.audience (id, name) VALUES (8, 'Aula 381');
INSERT INTO lesson_parsing.audience (id, name) VALUES (248, 'Aula 382');
INSERT INTO lesson_parsing.audience (id, name) VALUES (20, 'Aula 383');
INSERT INTO lesson_parsing.audience (id, name) VALUES (13, 'Aula 384');
INSERT INTO lesson_parsing.audience (id, name) VALUES (16, 'Aula 385');
INSERT INTO lesson_parsing.audience (id, name) VALUES (243, 'Aula 386');
INSERT INTO lesson_parsing.audience (id, name) VALUES (707, 'Aula 387');
INSERT INTO lesson_parsing.audience (id, name) VALUES (71, 'Aula 390');
INSERT INTO lesson_parsing.audience (id, name) VALUES (72, 'Aula 392');
INSERT INTO lesson_parsing.audience (id, name) VALUES (73, 'Aula 393');
INSERT INTO lesson_parsing.audience (id, name) VALUES (249, 'Aula 394');
INSERT INTO lesson_parsing.audience (id, name) VALUES (246, 'Aula 4');
INSERT INTO lesson_parsing.audience (id, name) VALUES (226, 'Aula 401');
INSERT INTO lesson_parsing.audience (id, name) VALUES (286, 'Aula 402');
INSERT INTO lesson_parsing.audience (id, name) VALUES (11, 'Aula 404');
INSERT INTO lesson_parsing.audience (id, name) VALUES (100, 'Aula 406');
INSERT INTO lesson_parsing.audience (id, name) VALUES (200, 'Aula 411');
INSERT INTO lesson_parsing.audience (id, name) VALUES (142, 'Aula 412');
INSERT INTO lesson_parsing.audience (id, name) VALUES (101, 'Aula 413');
INSERT INTO lesson_parsing.audience (id, name) VALUES (102, 'Aula 414');
INSERT INTO lesson_parsing.audience (id, name) VALUES (706, 'Aula 415');
INSERT INTO lesson_parsing.audience (id, name) VALUES (705, 'Aula 416');
INSERT INTO lesson_parsing.audience (id, name) VALUES (103, 'Aula 417');
INSERT INTO lesson_parsing.audience (id, name) VALUES (104, 'Aula 419');
INSERT INTO lesson_parsing.audience (id, name) VALUES (105, 'Aula 420');
INSERT INTO lesson_parsing.audience (id, name) VALUES (106, 'Aula 421');
INSERT INTO lesson_parsing.audience (id, name) VALUES (107, 'Aula 423');
INSERT INTO lesson_parsing.audience (id, name) VALUES (108, 'Aula 424');
INSERT INTO lesson_parsing.audience (id, name) VALUES (109, 'Aula 425');
INSERT INTO lesson_parsing.audience (id, name) VALUES (704, 'Aula 426');
INSERT INTO lesson_parsing.audience (id, name) VALUES (297, 'Aula 427');
INSERT INTO lesson_parsing.audience (id, name) VALUES (110, 'Aula 428');
INSERT INTO lesson_parsing.audience (id, name) VALUES (111, 'Aula 429');
INSERT INTO lesson_parsing.audience (id, name) VALUES (112, 'Aula 430');
INSERT INTO lesson_parsing.audience (id, name) VALUES (113, 'Aula 431');
INSERT INTO lesson_parsing.audience (id, name) VALUES (114, 'Aula 432');
INSERT INTO lesson_parsing.audience (id, name) VALUES (50, 'Aula 433');
INSERT INTO lesson_parsing.audience (id, name) VALUES (35, 'Aula 434');
INSERT INTO lesson_parsing.audience (id, name) VALUES (115, 'Aula 435');
INSERT INTO lesson_parsing.audience (id, name) VALUES (116, 'Aula 436');
INSERT INTO lesson_parsing.audience (id, name) VALUES (117, 'Aula 437');
INSERT INTO lesson_parsing.audience (id, name) VALUES (118, 'Aula 438');
INSERT INTO lesson_parsing.audience (id, name) VALUES (51, 'Aula 439');
INSERT INTO lesson_parsing.audience (id, name) VALUES (119, 'Aula 440');
INSERT INTO lesson_parsing.audience (id, name) VALUES (120, 'Aula 441');
INSERT INTO lesson_parsing.audience (id, name) VALUES (121, 'Aula 442');
INSERT INTO lesson_parsing.audience (id, name) VALUES (122, 'Aula 443');
INSERT INTO lesson_parsing.audience (id, name) VALUES (123, 'Aula 444');
INSERT INTO lesson_parsing.audience (id, name) VALUES (124, 'Aula 445');
INSERT INTO lesson_parsing.audience (id, name) VALUES (125, 'Aula 446');
INSERT INTO lesson_parsing.audience (id, name) VALUES (126, 'Aula 447');
INSERT INTO lesson_parsing.audience (id, name) VALUES (127, 'Aula 448');
INSERT INTO lesson_parsing.audience (id, name) VALUES (128, 'Aula 449');
INSERT INTO lesson_parsing.audience (id, name) VALUES (129, 'Aula 450');
INSERT INTO lesson_parsing.audience (id, name) VALUES (130, 'Aula 451');
INSERT INTO lesson_parsing.audience (id, name) VALUES (131, 'Aula 452');
INSERT INTO lesson_parsing.audience (id, name) VALUES (132, 'Aula 453');
INSERT INTO lesson_parsing.audience (id, name) VALUES (133, 'Aula 454');
INSERT INTO lesson_parsing.audience (id, name) VALUES (134, 'Aula 455');
INSERT INTO lesson_parsing.audience (id, name) VALUES (93, 'Aula 456');
INSERT INTO lesson_parsing.audience (id, name) VALUES (94, 'Aula 457');
INSERT INTO lesson_parsing.audience (id, name) VALUES (135, 'Aula 459');
INSERT INTO lesson_parsing.audience (id, name) VALUES (137, 'Aula 460');
INSERT INTO lesson_parsing.audience (id, name) VALUES (136, 'Aula 461');
INSERT INTO lesson_parsing.audience (id, name) VALUES (138, 'Aula 463');
INSERT INTO lesson_parsing.audience (id, name) VALUES (139, 'Aula 464');
INSERT INTO lesson_parsing.audience (id, name) VALUES (140, 'Aula 465');
INSERT INTO lesson_parsing.audience (id, name) VALUES (141, 'Aula 466');
INSERT INTO lesson_parsing.audience (id, name) VALUES (251, 'Aula 5009');
INSERT INTO lesson_parsing.audience (id, name) VALUES (143, 'Aula 501');
INSERT INTO lesson_parsing.audience (id, name) VALUES (42, 'Aula 5011');
INSERT INTO lesson_parsing.audience (id, name) VALUES (181, 'Aula 5012');
INSERT INTO lesson_parsing.audience (id, name) VALUES (43, 'Aula 5014');
INSERT INTO lesson_parsing.audience (id, name) VALUES (18, 'Aula 5015');
INSERT INTO lesson_parsing.audience (id, name) VALUES (27, 'Aula 5016');
INSERT INTO lesson_parsing.audience (id, name) VALUES (38, 'Aula 5017');
INSERT INTO lesson_parsing.audience (id, name) VALUES (180, 'Aula 5018');
INSERT INTO lesson_parsing.audience (id, name) VALUES (265, 'Aula 502');
INSERT INTO lesson_parsing.audience (id, name) VALUES (257, 'Aula 5021');
INSERT INTO lesson_parsing.audience (id, name) VALUES (195, 'Aula 503');
INSERT INTO lesson_parsing.audience (id, name) VALUES (170, 'Aula 505');
INSERT INTO lesson_parsing.audience (id, name) VALUES (168, 'Aula 506');
INSERT INTO lesson_parsing.audience (id, name) VALUES (169, 'Aula 507');
INSERT INTO lesson_parsing.audience (id, name) VALUES (172, 'Aula 508');
INSERT INTO lesson_parsing.audience (id, name) VALUES (260, 'Aula 510');
INSERT INTO lesson_parsing.audience (id, name) VALUES (86, 'Aula 512');
INSERT INTO lesson_parsing.audience (id, name) VALUES (218, 'Aula 513');
INSERT INTO lesson_parsing.audience (id, name) VALUES (87, 'Aula 516');
INSERT INTO lesson_parsing.audience (id, name) VALUES (88, 'Aula 519');
INSERT INTO lesson_parsing.audience (id, name) VALUES (193, 'Aula 520');
INSERT INTO lesson_parsing.audience (id, name) VALUES (196, 'Aula 520A');
INSERT INTO lesson_parsing.audience (id, name) VALUES (177, 'Aula 521');
INSERT INTO lesson_parsing.audience (id, name) VALUES (178, 'Aula 523');
INSERT INTO lesson_parsing.audience (id, name) VALUES (89, 'Aula 525');
INSERT INTO lesson_parsing.audience (id, name) VALUES (182, 'Aula 531');
INSERT INTO lesson_parsing.audience (id, name) VALUES (75, 'Aula 532');
INSERT INTO lesson_parsing.audience (id, name) VALUES (74, 'Aula 533');
INSERT INTO lesson_parsing.audience (id, name) VALUES (202, 'Aula 534');
INSERT INTO lesson_parsing.audience (id, name) VALUES (306, 'Aula 535');
INSERT INTO lesson_parsing.audience (id, name) VALUES (47, 'Aula 536');
INSERT INTO lesson_parsing.audience (id, name) VALUES (201, 'Aula 537');
INSERT INTO lesson_parsing.audience (id, name) VALUES (264, 'Aula 540');
INSERT INTO lesson_parsing.audience (id, name) VALUES (145, 'Aula 541');
INSERT INTO lesson_parsing.audience (id, name) VALUES (146, 'Aula 542');
INSERT INTO lesson_parsing.audience (id, name) VALUES (147, 'Aula 543');
INSERT INTO lesson_parsing.audience (id, name) VALUES (197, 'Aula 543A');
INSERT INTO lesson_parsing.audience (id, name) VALUES (41, 'Aula 545');
INSERT INTO lesson_parsing.audience (id, name) VALUES (280, 'Aula 546');
INSERT INTO lesson_parsing.audience (id, name) VALUES (148, 'Aula 547');
INSERT INTO lesson_parsing.audience (id, name) VALUES (37, 'Aula 549');
INSERT INTO lesson_parsing.audience (id, name) VALUES (149, 'Aula 553');
INSERT INTO lesson_parsing.audience (id, name) VALUES (150, 'Aula 554');
INSERT INTO lesson_parsing.audience (id, name) VALUES (151, 'Aula 555');
INSERT INTO lesson_parsing.audience (id, name) VALUES (152, 'Aula 556');
INSERT INTO lesson_parsing.audience (id, name) VALUES (153, 'Aula 557');
INSERT INTO lesson_parsing.audience (id, name) VALUES (154, 'Aula 558');
INSERT INTO lesson_parsing.audience (id, name) VALUES (155, 'Aula 559');
INSERT INTO lesson_parsing.audience (id, name) VALUES (217, 'Aula 563');
INSERT INTO lesson_parsing.audience (id, name) VALUES (252, 'Aula 564');
INSERT INTO lesson_parsing.audience (id, name) VALUES (221, 'Aula 565');
INSERT INTO lesson_parsing.audience (id, name) VALUES (156, 'Aula 566');
INSERT INTO lesson_parsing.audience (id, name) VALUES (157, 'Aula 567');
INSERT INTO lesson_parsing.audience (id, name) VALUES (158, 'Aula 568');
INSERT INTO lesson_parsing.audience (id, name) VALUES (159, 'Aula 569');
INSERT INTO lesson_parsing.audience (id, name) VALUES (160, 'Aula 570');
INSERT INTO lesson_parsing.audience (id, name) VALUES (227, 'Aula 572');
INSERT INTO lesson_parsing.audience (id, name) VALUES (26, 'Aula 575');
INSERT INTO lesson_parsing.audience (id, name) VALUES (161, 'Aula 576');
INSERT INTO lesson_parsing.audience (id, name) VALUES (162, 'Aula 577');
INSERT INTO lesson_parsing.audience (id, name) VALUES (163, 'Aula 578');
INSERT INTO lesson_parsing.audience (id, name) VALUES (164, 'Aula 579');
INSERT INTO lesson_parsing.audience (id, name) VALUES (244, 'Aula 580');
INSERT INTO lesson_parsing.audience (id, name) VALUES (165, 'Aula 581');
INSERT INTO lesson_parsing.audience (id, name) VALUES (76, 'Aula 582');
INSERT INTO lesson_parsing.audience (id, name) VALUES (77, 'Aula 583');
INSERT INTO lesson_parsing.audience (id, name) VALUES (78, 'Aula 584');
INSERT INTO lesson_parsing.audience (id, name) VALUES (79, 'Aula 585');
INSERT INTO lesson_parsing.audience (id, name) VALUES (80, 'Aula 586');
INSERT INTO lesson_parsing.audience (id, name) VALUES (81, 'Aula 587');
INSERT INTO lesson_parsing.audience (id, name) VALUES (82, 'Aula 588');
INSERT INTO lesson_parsing.audience (id, name) VALUES (83, 'Aula 589');
INSERT INTO lesson_parsing.audience (id, name) VALUES (84, 'Aula 590');
INSERT INTO lesson_parsing.audience (id, name) VALUES (216, 'Aula 593');
INSERT INTO lesson_parsing.audience (id, name) VALUES (166, 'Aula 594');
INSERT INTO lesson_parsing.audience (id, name) VALUES (5, 'Aula 595');
INSERT INTO lesson_parsing.audience (id, name) VALUES (185, 'Aula 597');
INSERT INTO lesson_parsing.audience (id, name) VALUES (176, 'Aula 598');
INSERT INTO lesson_parsing.audience (id, name) VALUES (85, 'Aula 599');
INSERT INTO lesson_parsing.audience (id, name) VALUES (291, 'Aula 600');
INSERT INTO lesson_parsing.audience (id, name) VALUES (292, 'Aula 606');
INSERT INTO lesson_parsing.audience (id, name) VALUES (308, 'Aula 611');
INSERT INTO lesson_parsing.audience (id, name) VALUES (231, 'Aula 623');
INSERT INTO lesson_parsing.audience (id, name) VALUES (253, 'Aula 624');
INSERT INTO lesson_parsing.audience (id, name) VALUES (183, 'Aula 625');
INSERT INTO lesson_parsing.audience (id, name) VALUES (144, 'Aula 626');
INSERT INTO lesson_parsing.audience (id, name) VALUES (187, 'Aula 627');
INSERT INTO lesson_parsing.audience (id, name) VALUES (188, 'Aula 628');
INSERT INTO lesson_parsing.audience (id, name) VALUES (54, 'Aula 630');
INSERT INTO lesson_parsing.audience (id, name) VALUES (186, 'Aula 632');
INSERT INTO lesson_parsing.audience (id, name) VALUES (194, 'Aula 633');
INSERT INTO lesson_parsing.audience (id, name) VALUES (220, 'Aula 634');
INSERT INTO lesson_parsing.audience (id, name) VALUES (189, 'Aula 635');
INSERT INTO lesson_parsing.audience (id, name) VALUES (224, 'Aula 636');
INSERT INTO lesson_parsing.audience (id, name) VALUES (279, 'Aula 639');
INSERT INTO lesson_parsing.audience (id, name) VALUES (229, 'Aula 642');
INSERT INTO lesson_parsing.audience (id, name) VALUES (191, 'Aula 644');
INSERT INTO lesson_parsing.audience (id, name) VALUES (53, 'Aula 645');
INSERT INTO lesson_parsing.audience (id, name) VALUES (190, 'Aula 646');
INSERT INTO lesson_parsing.audience (id, name) VALUES (198, 'Aula 646A');
INSERT INTO lesson_parsing.audience (id, name) VALUES (262, 'Aula 647');
INSERT INTO lesson_parsing.audience (id, name) VALUES (263, 'Aula 648');
INSERT INTO lesson_parsing.audience (id, name) VALUES (287, 'Aula 651');
INSERT INTO lesson_parsing.audience (id, name) VALUES (192, 'Aula 652');
INSERT INTO lesson_parsing.audience (id, name) VALUES (230, 'Aula 653');
INSERT INTO lesson_parsing.audience (id, name) VALUES (245, 'Aula 6543');
INSERT INTO lesson_parsing.audience (id, name) VALUES (250, 'Aula 655');
INSERT INTO lesson_parsing.audience (id, name) VALUES (175, 'Aula 656');
INSERT INTO lesson_parsing.audience (id, name) VALUES (235, 'Aula 665');
INSERT INTO lesson_parsing.audience (id, name) VALUES (234, 'Aula 666');
INSERT INTO lesson_parsing.audience (id, name) VALUES (91, 'Aula 667');
INSERT INTO lesson_parsing.audience (id, name) VALUES (92, 'Aula 668');
INSERT INTO lesson_parsing.audience (id, name) VALUES (247, 'Aula 669');
INSERT INTO lesson_parsing.audience (id, name) VALUES (210, 'Aula 801');
INSERT INTO lesson_parsing.audience (id, name) VALUES (273, 'Aula 802');
INSERT INTO lesson_parsing.audience (id, name) VALUES (232, 'Aula 808');
INSERT INTO lesson_parsing.audience (id, name) VALUES (203, 'Aula 811');
INSERT INTO lesson_parsing.audience (id, name) VALUES (212, 'Aula 813');
INSERT INTO lesson_parsing.audience (id, name) VALUES (213, 'Aula 814');
INSERT INTO lesson_parsing.audience (id, name) VALUES (293, 'Aula 818');
INSERT INTO lesson_parsing.audience (id, name) VALUES (211, 'Aula 825');
INSERT INTO lesson_parsing.audience (id, name) VALUES (209, 'Aula 826');
INSERT INTO lesson_parsing.audience (id, name) VALUES (208, 'Aula 827');
INSERT INTO lesson_parsing.audience (id, name) VALUES (215, 'Aula 839');
INSERT INTO lesson_parsing.audience (id, name) VALUES (207, 'Aula 843');
INSERT INTO lesson_parsing.audience (id, name) VALUES (204, 'Aula 845');
INSERT INTO lesson_parsing.audience (id, name) VALUES (214, 'Aula 849');

INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8804, 'NEW_USER', 120, '17/03/2021 22:34:52', '/start', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8805, 'GROUP', 120, '17/03/2021 22:34:56', 'Hariton Natalia Ivan', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8806, 'GROUP', 120, '17/03/2021 22:35:51', 'DM11M', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8807, 'GROUP', 120, '17/03/2021 22:35:54', 'Teacher', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8808, 'GROUP', 120, '17/03/2021 22:35:57', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8809, 'GROUP', 120, '17/03/2021 22:38:23', 'Teacher', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8810, 'GROUP', 120, '17/03/2021 22:38:52', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8811, 'GROUP', 120, '17/03/2021 23:00:18', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8812, 'GROUP', 120, '17/03/2021 23:00:20', 'Teacher', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8813, 'GROUP', 120, '17/03/2021 23:03:45', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8814, 'GROUP', 120, '17/03/2021 23:03:48', 'Teacher', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8815, 'GROUP', 120, '17/03/2021 23:07:28', 'Teacher', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8816, 'GROUP', 120, '17/03/2021 23:07:30', 'Audience', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8817, 'GROUP', 120, '17/03/2021 23:07:49', 'Teacher', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8818, 'GROUP', 120, '17/03/2021 23:15:28', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8819, 'GROUP', 120, '17/03/2021 23:15:30', 'Teacher', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8820, 'GROUP', 120, '18/03/2021 11:17:28', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8822, 'GROUP', 120, '18/03/2021 11:18:52', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8823, 'GROUP', 120, '18/03/2021 11:19:19', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8824, 'GROUP', 120, '18/03/2021 11:41:51', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8825, 'GROUP', 120, '18/03/2021 11:45:45', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8826, 'GROUP', 120, '18/03/2021 11:45:53', 'Teacher', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8827, 'GROUP', 120, '18/03/2021 12:41:11', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8828, 'GROUP', 120, '18/03/2021 18:16:23', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8829, 'GROUP', 120, '19/03/2021 14:21:35', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8831, 'GROUP', 120, '26/03/2021 12:34:17', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8833, 'GROUP', 120, '26/03/2021 12:43:30', 'Group', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8834, 'GROUP', 120, '26/03/2021 12:43:35', 'ba31z', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8835, 'GROUP', 120, '26/03/2021 12:43:53', 'ba31z', 972344705, null);
INSERT INTO history_data.history (id, event, user_id, request_date, request_message, user_chat_id, chat_id) VALUES (8836, 'GROUP', 120, '26/03/2021 12:44:42', 'ba31z', 972344705, null);